### ISSUE TITLE
Remove auxiliary files

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/workshop-rasax-short#1]
There are a couple files in the git repo that shouldn't be checked in:
- .`DS_STORE` (every folder)
- `__pycache__`
- rasa.db / tracker.db (not sure about these ones, depends on your use case - they contain the rasa x database)

**Comment by TyDunn** [comment]
Added `.DS_STORE` and `__pycache__` to .gitignore and applied it. I want rasa.db / tracker.db, so that they are there for people when start Rasa X.

Btw to create this, I just forked and simplified Juste's [workshop-rasax repo](https://github.com/RasaHQ/workshop-rasax), so the same issues should be created there as well.
